server:
  port: 8081
  servlet:
    context-path: /zyj/admin
spring:
  application:
    name: zhenyaojian
  profiles:
    active: dev
  mvc:
    hiddenmethod:
      filter:
        enabled: true # 开启 HiddenHttpMethodFilter 支持 restful 风格 URL
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  boot:
    admin:
      context-path: /observe/server
      client:
        url: http://localhost:8081/zyj/admin/observe/server
zyj:
  # 重置用户密码时的默认密码
  default-password: SunChaser666
  # JWT 配置
  jwt:
    sign-type: public_private_key
    secret: K7S8Kri2kAdzFOTTz1Emf8bVN/L+Gku4i9CqMVs7+j8=
    public-key-location: public.key
    private-key-location: private.key
management:
  endpoints:
    web:
      exposure:
        include: "*"
