spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sunchaser_zyj?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
zyj:
  # 重置用户密码时的默认密码
  default-password: SunChaser
